config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :pictures
  end
  get 'products/index'
  
  root 'products#index'

end

app/models/product.rb
class Product < ApplicationRecord
  filterrific :default_filter_params => { :sorted_by => 'created_at_desc' },
                :available_filters => [
                  :sorted_by,
                  :search_query,
                  :with_min_price,
                  :with_max_price,
                  :with_category_id,
                  :with_brand_id,
                  :with_created_at_gte
                ]

    # default for will_paginate
    self.per_page = 9

    belongs_to :category
    belongs_to :brand
    #has_many :picture, dependent: :destroy
    # tell the model to accept the nested attributes for attached_assets
    #accepts_nested_attributes_for :picture
    # CarrierWave
    has_many :pictures, dependent: :destroy
    
    #accepts_nested_attributes_for :pictures

    # mount_uploader :image, ImageUploader
    # has_many :image, dependent: :destroy
    #accepts_nested_attributes_for :pictures
    # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    scope :search_query, lambda { |query|
      return nil  if query.blank?
      # condition query, parse into individual keywords
      terms = query.downcase.split(/\s+/)
      # replace "*" with "%" for wildcard searches,
      # append '%', remove duplicate '%'s
      terms = terms.map { |e|
        (e.gsub('*', '%') + '%').gsub(/%+/, '%')
      }
      # configure number of OR conditions for provision
      # of interpolation arguments. Adjust this if you
      # change the number of OR conditions.
      num_or_conditions = 3
      where(
        terms.map {
          or_clauses = [
            "LOWER(products.name) LIKE ?",
            "LOWER(products.name) LIKE ?",
            "LOWER(products.description) LIKE ?"
          ].join(' OR ')
          "(#{ or_clauses })"
        }.join(' AND '),
        *terms.map { |e| [e] * num_or_conditions }.flatten
      )
    }
    scope :with_min_price, lambda { |min_price|
      where('products.price >= ?', min_price)
    }
    scope :with_max_price, lambda { |max_price|
      where('products.price <= ?', max_price)
    }
    scope :sorted_by, lambda { |sort_option|
      # extract the sort direction from the param value.
      direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
      case sort_option.to_s
      when /^created_at_/
        order("products.created_at #{ direction }")
      when /^price_/
        order("products.price #{ direction }")
      when /^name_/
        order("LOWER(products.name) #{ direction }")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
      end
    }
    
    scope :with_category_id, lambda { |category_ids|
      where(:category_id => [*category_ids])
    }
    scope :with_brand_id, lambda { |brand_ids|
      where(:brand_id => [*brand_ids])
    }
    scope :with_created_at_gte, lambda { |ref_date|
      where('products.created_at >= ?', ref_date)
    }

    delegate :name, :to => :category, :prefix => true
    delegate :name, :to => :brand, :prefix => true

    def self.options_for_sorted_by
      [
        ['Registration date (newest first)', 'created_at_desc'],
        ['Registration date (oldest first)', 'created_at_asc'],
        ['Price (low to high)', 'price_asc'],
        ['Price (high to low)', 'price_desc'],
        ['Name (a-z)', 'name_asc']
      ]
    end

    # def full_name
    #   [last_name, first_name].compact.join(', ')
    # end

    def decorated_created_at
      created_at.to_date.to_s(:long)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      select_options: {
        sorted_by: Product.options_for_sorted_by,
        with_category_id: Category.options_for_select,
        with_brand_id: Brand.options_for_select
      }
    ) or return
    @products = @filterrific.find.page(params[:page])
    # @products = Product.all
    #@uploads = Picture.order('created_at ASC')  

        respond_to do |format|
          format.html
          format.js
        end
  end
  def list
  end

  def grid
  end
  def show
    @category = Category.find_by_id(params[:category_id])
    @brand = Brand.find_by_id(params[:brand_id])
    # @products = Product.all.order("name DESC")
    @product = Product.find(params[:id])
    @picture = Picture.where(product_id: @product.id).order("created_at ASC") 
    # @image = Picture.first
    #@pictures = @product.pictures.all
  end

  def new
    @product = Product.new
    #@pictures = @product.pictures.build
  end

  def create
    
    @product = Product.new(product_params)

    respond_to do |format| 
       if @product.save 
          # params[:pictures]['image'].each do |a|
          #   @pictures = @product.pictures.create!(:image => a)
          # end
          format.html { redirect_to @product, notice: "Product was successfully created." } 
          format.json { render :show, status: :created, location: @product } 
       else 
          format.html { render :new, notice: "You have a error" } 
          format.json { render json: @product.errors, status: :unprocessable_entity } 
       end 
     end
  end

  def edit
    
  end

  def update
    
    if @product.update(product_params)
      redirect_to @product, notice: "Your product was updated !"
    else
      render "edit"
    end
  end

  def destroy
    
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private

  def product_params
   params.require(:product).permit( :id, :name, :description, :price, :category_id, :brand_id, :image,
     :product_id)
   
  end

  def set_product
    @product = Product.find(params[:id])
  end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.container.col-md-10.col-sm-10.col-xs-12
  #categories
    = simple_form_for(@product, html: { class: '' }, multipart: true ) do |f|
      
      = f.input :name, label: "Product Name", input_html: {class: "form-control" }
      %br/
      %label Category
      = f.collection_select(:category_id, Category.all, :id, :name, prompt: true)
      %br/
      %br/
      %label Brand
      = f.collection_select(:brand_id, Brand.all, :id, :name, prompt: true)
      
      %br/
      %br/
      / = render :partial => 'pictures/form', remote: true,:locals => { :products => @products }
      / %br/
      / %br/
      
      = f.input :description, label: "Product Description", input_html: {class: "form-control" }
      
      = f.input :price, label: "Price", input_html: {class: "form-control" }
      %br/
      = f.button :submit, class: "btn btn-default"

app/views/products/_grid.html.haml
.container
  #filterrific_results
    .row
      .col-md-7.col-sm-6.col-xs-12
        .pagins.chardin_box{ :'data-position' => 'top', :'data-intro' => "will_paginate's paginator works as expected." }
          = will_paginate @products, renderer: BootstrapPagination::Rails
      .col-md-4.col-sm-4
        .chardin_box.info-page{ :'data-position' => 'bottom', :'data-intro' => "will_paginate's entries info works as expected." }
          = page_entries_info @products, :model => 'product'
        .chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Spinner indicates update.' }
          = render_filterrific_spinner
    .row
      #pins.transitions-enabled
        -@products.each do |product|
          .box.panel.panel-default.col-sm-6.col-md-3.col-xs-12 
            .front_image
              - if product.pictures.blank?
                .no-image
                  = image_tag("no-image-available.png",  alt: "bicycle-01", class: "img-responsive") 
              -else
                = link_to image_tag(product.pictures.first.image_url(:thumb).to_s), product 
            .panel-body
              %h4= link_to truncate(product.name, :length => 20), product, { style: 'text-decoration: underline;  font-weight: 500;' }
              .price
                %p.price_tag
                  = number_to_currency(product.price)
              %p
                Created at - 
                = product.created_at.to_date.to_s(:long)
            / %hr
    .chardin_box{ :'data-position' => 'top', :'data-intro' => "will_paginate's paginator works as expected." }
      = will_paginate @products, renderer: BootstrapPagination::Rails

app/views/products/_list.html.haml
#filterrific_results
  .row
    .col-md-8.col-sm-8
      .chardin_box{ :'data-position' => 'top', :'data-intro' => "will_paginate's paginator works as expected." }
        = will_paginate @products, renderer: BootstrapPagination::Rails
      
    .col-md-4.col-sm-4
      .chardin_box.info-page{ :'data-position' => 'bottom', :'data-intro' => "will_paginate's entries info works as expected." }
        = page_entries_info @products, :model => 'product'
      .chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Spinner indicates update.' }
        = render_filterrific_spinner
  .row
    #pins
      -@products.each do |product|
        .box.panel.panel-default  
          %h4= link_to product.name, product, { style: 'text-decoration: underline;  font-weight: 500;' }
          %p.price_tag
            $ 
            = product.price
          %p
            Created at - 
            = product.created_at.to_date.to_s(:long)
          %hr
  .chardin_box{ :'data-position' => 'top', :'data-intro' => "will_paginate's paginator works as expected." }
    = will_paginate @products, renderer: BootstrapPagination::Rails
    

app/views/products/_picture_fields.html.haml
.nested-fields
  .field
    = f.label :type_of
    = f.select :type_of, [ 'First Type', 'Second Type' ], :required => true
  .field
    = f.label :image, "File to submit"
    = f.file_field :image, :required => true
  = link_to_remove_association "Remove file", f

app/views/products/edit.html.haml
#products.col-md-10.col-sm-10.col-xs-12  
  %h1 Edit Product

  = render 'form'

app/views/products/grid.js.erb
$('.product-list').html("<%= j render :partial => 'grid' %>");

app/views/products/index.html.haml
/ %h1 Products
= form_for_filterrific( @filterrific, url: products_path , html: { id: :manual_filterrific_form }) do |f|
  
  .top_filters
    .row
      .col-sm-6.col-md-6.sorted_by
        .chardin_box{ :'data-position' => 'top', :'data-intro' => 'Change the sorting.' }
          %label Sorted by
          = f.select :sorted_by, @filterrific.select_options[:sorted_by],{},{ :class => 'filterrific-periodically-observed ' }
      / .col-md-1.buttons
      /   = link_to  :partial => 'products/list' , :id => 'list', remote: true do
      /     %span.glyphicon.glyphicon-th-list
      /   = link_to  :partial => 'products/grid', :id => 'grid', remote: true do
      /     %span.glyphicon.glyphicon-th

      .col-sm-6.col-md-6.search-product
        .chardin_box{ :'data-position' => 'top', :'data-intro' => 'Search by first name, last name, or email.', }
          = f.text_field :search_query, placeholder: " Search...",:class => 'filterrific-periodically-observed search'
        
          / = f.button :submit do |f|
          /   %i.glyphicon.glyphicon-search 
  .separator
    %hr  
  / %button{ :'data-target' => "#demo", :'type' => "button" ,:class =>'btn btn-info ', :'data-toggle'=>"collapse"} Simple Button

  .row  
    .filter-zone.col-md-2.col-sm-2
      .left-filtering.form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Filter by category.' }
        %label Category
        = f.select(:with_category_id, @filterrific.select_options[:with_category_id], { :include_blank => '- Any -' },{ :class => 'form-control filterrific-periodically-observed' })

      .left-filtering.form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Filter by brand.' }
        %label Brand
        = f.select(:with_brand_id, @filterrific.select_options[:with_brand_id],{ :include_blank => '- Any -' },{ :class => 'form-control filterrific-periodically-observed' })
      .left-filtering
        %label Price
        = f.text_field(:with_min_price,{ :class => 'form-control filterrific-periodically-observed ', placeholder: "min" })
      .left-filtering 
        = f.text_field(:with_max_price,{ :class => 'form-control filterrific-periodically-observed ', placeholder: "max" })
          
      / .left-filtering
          
      / = f.submit "Update",{ :class => 'btn btn-sm btn-primary left-filtering ' }
      / %br
      / %br
      .left-filtering{ :'data-position' => 'bottom', :'data-intro' => 'Reset the filter settings to defaults.' }
        = link_to "Reset filters", reset_filterrific_url, :class => 'btn btn-info'
    
  
    .product-list.col-md-10.col-sm-10
      = render :partial => 'products/grid', remote: true,:locals => { :products => @products }
  
    
  :javascript
    
    $('#overlayTrigger').click(function(event) {
      event.preventDefault();
      $('body').chardinJs('start');
    }); 
  

app/views/products/index.js.erb
<% js = escape_javascript(
  
  
    render(
  #     $(".buttons").onclick(function () {
  #   if ($(this).hasId('grid')) {

  #   }else{

  #   }

  # });

      :partial => 'products/grid',
      :locals => { :products => @products }
    )
  

    
) %>
$("#filterrific_results").html("<%= js %>");

app/views/products/list.js.erb
$('.product-list').html("<%= j render :partial => 'list' %>");

app/views/products/new.html.haml
.container
  %h3 New Product

  = render 'form'
  %br/
  %br/
  %br/
  = link_to "Back", root_path, class: "btn btn-primary"

app/views/products/show.html.haml
.container
  
  .show-product
    .row
      .col-sm-12.col-md-6 
        - if @picture.blank?
          %h3 No photo yet
        -else
         
          .main_image
            = image_tag @picture.first.image_url().to_s, class: 'custom img-responsive'
          
          - @picture.each do |picture|
            
            %ul.thumbnails
              %li
                =link_to picture.image_url(picture) do
                  =image_tag picture.image_url(:small_thumb).to_s, class: 'thumbnails_img img-responsive'

                .link_img  
                  - if current_user.try(:admin?)
                    = link_to "Remove", product_picture_path(@product, picture), method: :delete, data: { confirm: "Are you sure ?" }, class: "btn btn-sm btn-danger"

      .col-sm-12.col-md-6.details
        %h3= @product.name
        %hr
        %p.description= simple_format(@product.description)
        .price
          %p
            = number_to_currency(@product.price)
              
          %br/
          #links
            = link_to "Back", :back, class: "btn btn-sm btn-default"
            - if current_user.try(:admin?)
              = link_to "Add Image", new_product_picture_path(@product), class: "btn btn-sm btn-default"
              = link_to "Edit", edit_product_path(@product), class: "btn btn-sm btn-default"
              = link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure ?" }, class: "btn btn-sm btn-default"