config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :pictures
  end
  get 'products/index'
  
  root 'products#index'

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Electro Market
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0"}
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags


%body
  %nav.navbar.navbar-default
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand= link_to "Electro Market", root_path
      .collapse.navbar-collapse.navbar-ex1-collapse
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Add Product", new_product_path
            %li= link_to "Account", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path,   method: :delete
            %p
              Welcome: 
              = current_user.email
            
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sing Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path  
            
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info", id:"alert-info"
    = yield


   
  